apiVersion: v1
kind: Service
metadata:
  name: fems
  labels:
    name: fems
    app: product-availability
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  selector:
    name: fems-nodeport
    app: product-availability
