apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: product-availability
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ui
      app: product-availability
  template:
    metadata:
      name: ui
      labels:
        name: ui
        app: product-availability

    spec:
      containers:
        - name: ui
          image: mniyonshuti/ui
          ports:
            - containerPort: 4200
