apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    name: ui
    app: product-availability
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30010
  selector:
    name: ui
    app: product-availability
